spring.application.name=modile-banking-aba

#
spring.datasource.url=jdbc:postgresql://localhost:4000/cardb
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=seng4321

#spring.security.user.name=seng
#spring.security.user.password=se
# create-drop: Create and then destroy the schema at the end of the session

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true